package com.transferchain.random;

import java.util.Arrays;

import java.security.SecureRandom;
import org.apache.cordova.CallbackContext;
import org.apache.cordova.CordovaPlugin;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public final class Random extends CordovaPlugin {

    // Generation runs off the UI thread. After callback delivery, finally
    // wipes the temporary result array owned by this call.
    @Override
    // DISPATCH AND CALLBACK PROTOCOL
    // true means the action was recognized, not that calculation succeeded. The
    // outer try/catch handles scheduling failure; the worker's try/catch handles
    // validation and provider failure after dispatch. One accepted request must
    // complete its callback once, with either binary output or a structured error.
    //
    // Cordova's thread pool schedules work; it does not validate input, impose a
    // memory budget, or wipe resources. Call-local ownership avoids shared mutable
    // KDF state. Dropping the JS Promise does not stop an already running native call.
    // UI work requires an explicit activity-thread handoff, never an assumption
    // that a pool thread has UI affinity.
    public boolean execute(String action, JSONArray args, CallbackContext callback) {
        if (!(action.equals("randomBytes"))) return false;

        try {
            cordova.getThreadPool().execute(() -> {
                try {
                    if (args.length() != 1 || !(args.opt(0) instanceof JSONObject)) {
                        throw invalid("Expected one options object.");
                    }

                    // Allocate only after native validation. Keep the result alive until Cordova
                    // has built its callback payload, then clear this local byte array.
                    byte[] result = perform(args.getJSONObject(0));

                    try {
                        callback.success(result);
                    } finally {
                        Arrays.fill(result, (byte) 0);
                    }
                } catch (CryptoFailure error) {
                    fail(callback, error.code, error.getMessage());
                } catch (OutOfMemoryError error) {
                    fail(callback, "RESOURCE_LIMIT", "Insufficient memory for the crypto operation.");
                } catch (Exception error) {
                    fail(callback, "OPERATION_FAILED", "Native Random operation failed.");
                }
            });
        } catch (RuntimeException error) {
            fail(callback, "OPERATION_FAILED", "Unable to schedule the crypto operation.");
        }

        return true;
    }

    // Check size before allocation. Use SecureRandom's OS entropy source;
    // do not add manual seeding or a Math.random-style fallback.
    static byte[] perform(JSONObject options) throws Exception {
        // GENERATION PIPELINE
        // First validate an integer byte count, then allocate exactly that many bytes,
        // then ask the OS-backed provider to fill the allocation. The size limit prevents
        // a malformed bridge request from allocating an arbitrary-sized result.
        //
        // A successful result has exactly the requested length; random bytes need not
        // be printable and can include zero. Do not treat zero bytes as an empty result.
        // Statistical appearance is not an error check: rely on provider success/failure,
        // and never retry solely because output happens to match a previous prefix.
        int length = integer(options, "length", 1, 1048576);

        byte[] output = new byte[length];

        // The provider seeds itself from the system. Reusing a fixed seed here would
        // make keys/IVs generated by callers predictable.
        new SecureRandom().nextBytes(output);
        return output;
    }

    private static int integer(JSONObject options, String name, int min, int max)
            throws CryptoFailure {
        Object value = options.opt(name);

        if (!(value instanceof Number)) throw invalid(name + " must be an integer.");

        double number = ((Number) value).doubleValue();

        if (!Double.isFinite(number) || number != Math.rint(number) || number < min || number > max) {
            throw invalid(name + " is outside the supported integer range.");
        }

        return (int) number;
    }

    private static CryptoFailure invalid(String message) {
        return new CryptoFailure("INVALID_ARGUMENT", message);
    }

    private static final class CryptoFailure extends Exception {
        final String code;

        CryptoFailure(String code, String message) {
            super(message);
            this.code = code;
        }
    }

    private static void fail(CallbackContext callback, String code, String message) {
        JSONObject error = new JSONObject();

        try {
            error.put("code", code);
            error.put("message", message);
            error.put("name", code.equals("INVALID_ARGUMENT") ? "ArgumentError" : "OperationError");
        } catch (JSONException impossible) {
            callback.error("Native crypto operation failed.");
            return;
        }

        callback.error(error);
    }
}
